# vim: set filetype=yaml.docker-compose :
services:
  www:
    build:
      context: ./www
      dockerfile: Dockerfile.dev
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - 3000:3000
    volumes:
      - ./www:/app
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - 8080:8080
    volumes:
      - ./api:/app
    environment:
      - DB_HOST=postgres
      - DB_NAME=shuron2025
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-user}
      - DB_PASSWORD=${DB_PASSWORD:-password}
  postgres:
    image: postgres:17.6
    environment:
      POSTGRES_DB: shuron2025
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local